name: cart_suggestion_core
description: A new Flutter package project.
version: 0.0.3
homepage:

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  slide_popup_dialog:
    git:
      url: https://github.com/victorevox/slide_popup_dialog.git

  jalali_calendar:
    path: ../jalali_calendar
  flutter_linear_datepicker: ^2.0.4
  cupertino_icons: ^1.0.2
  get: ^4.1.4
  http: ^0.13.3
  dio: ^4.0.0
  easy_localization: ^3.0.0
  google_sign_in: ^5.0.4
  shared_preferences: ^2.0.6
  persian_number_utility: ^1.1.2
  flutter_svg: ^1.1.6
  #  slide_popup_dialog: ^0.0.2
  photo_view: ^0.12.0
  fluttertoast: ^8.1.1
  screenshot: ^1.2.1
  path_provider: ^2.0.11
  image_cropper: ^1.4.1
  speech_to_text: ^5.4.3
  google_maps_flutter: ^2.0.8
  location: ^4.2.0
  another_xlider: ^1.0.0
  url_launcher: ^6.0.9
  flutter_inappwebview: ^5.3.2
  auto_size_text_pk: ^3.0.0
  audioplayers: ^0.19.1
  animated_flip_counter: ^0.1.2
  #  cached_network_image: ^3.1.0
  cupertino_will_pop_scope: ^1.1.0
  pull_to_refresh: ^2.0.0
  package_info_plus: ^1.3.0
  connectivity: ^3.0.6
  firebase_messaging: ^11.2.5
  firebase_core: ^1.11.0
  flutter_local_notifications: ^9.2.0
  modal_bottom_sheet: ^2.0.0
  uni_links: ^0.5.1
  dotted_line: ^3.1.0
  cached_network_image: ^3.2.2
  dotted_border: ^2.0.0+3
  image_picker: ^0.8.6
  file_picker: ^5.2.2
  persian_datetime_picker: ^2.5.0
  video_player: ^2.4.7
  flick_video_player: any
  vimeo_video_player: ^0.0.6
  numberpicker: ^2.1.1
  custom_pop_up_menu: ^1.2.4
  infinite_scroll_pagination:
    path: ../infinite_scroll_pagination-3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
